/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algo;

/**
 *
 * @author Swappy
 */
import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
public class DataEntry extends javax.swing.JFrame {
Connection conn;
PreparedStatement pst;
ResultSet rs;
    /**
     * Creates new form DataEntry
     */
    public DataEntry() {
        super("Data Entry");
        initComponents();
        conn = javaconnect.ConnectorDb();
        ButtonGroup bg1= new ButtonGroup();
            ButtonGroup bg2= new ButtonGroup();
            bg1.add(ar1);
            bg1.add(ar2);
            bg2.add(tr1);
            bg2.add(tr2);
            bg2.add(tr3);
    }

    /**
     *
     */
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ar1 = new javax.swing.JRadioButton();
        ar2 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        tr1 = new javax.swing.JRadioButton();
        tr2 = new javax.swing.JRadioButton();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        tr3 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        vogue = new javax.swing.JCheckBox();
        stomp = new javax.swing.JCheckBox();
        fantastic = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        fusion = new javax.swing.JCheckBox();
        basketball = new javax.swing.JCheckBox();
        pool = new javax.swing.JCheckBox();
        mrms = new javax.swing.JCheckBox();
        zorbing = new javax.swing.JCheckBox();
        picraaz = new javax.swing.JCheckBox();
        csgo = new javax.swing.JCheckBox();
        food = new javax.swing.JCheckBox();
        halla = new javax.swing.JCheckBox();
        soccer = new javax.swing.JCheckBox();
        ball = new javax.swing.JCheckBox();
        snaptext = new javax.swing.JCheckBox();
        fifa = new javax.swing.JCheckBox();
        nfs = new javax.swing.JCheckBox();
        pubg = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Booklet Number");

        jLabel2.setText("Receipt Number");

        jLabel3.setText("Name");

        jLabel4.setText("Father's Name");

        jLabel5.setText("Contact Number");

        jLabel6.setText("Email ID");

        jLabel7.setText("University CODE");

        jLabel8.setText("University ID");

        jLabel9.setText("Accomodation");

        ar1.setText("YES");
        ar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ar1ActionPerformed(evt);
            }
        });

        ar2.setText("NO");

        jLabel10.setText("Transportation");

        tr1.setText("43");
        tr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tr1ActionPerformed(evt);
            }
        });

        tr2.setText("17");

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });

        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });

        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });

        tr3.setText("No");

        jLabel12.setText("Event");

        vogue.setText("VOUGE");

        stomp.setText("STOMP THE YARD");
        stomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stompActionPerformed(evt);
            }
        });

        fantastic.setText("FANTASTIC TOE");

        jCheckBox4.setText("folklore");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        fusion.setText("EUPHONIOUS FUSION");

        basketball.setText("3 ON 3 BASKETBALL");

        pool.setText("8 BALLS OF FIRE");
        pool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poolActionPerformed(evt);
            }
        });

        mrms.setText("MR AND MS. ALGORYTHM");
        mrms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrmsActionPerformed(evt);
            }
        });

        zorbing.setText("ZORBING");

        picraaz.setText("PICRAAZ");

        csgo.setText("CSGO");

        food.setText("FOOD WITHOUT FIRE");

        halla.setText("halla");
        halla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hallaActionPerformed(evt);
            }
        });

        soccer.setText("4 A SIDE SOCCER");

        ball.setText("PAINT BALL");

        snaptext.setText("SNAPTEXT");

        fifa.setText("FIFA'19");

        nfs.setText("NEED FOR SPEED");

        pubg.setText("PUBG");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tr3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tr1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ar2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(tr2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(277, 277, 277)
                                .addComponent(jLabel12)
                                .addGap(260, 260, 260))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vogue)
                                    .addComponent(fantastic)
                                    .addComponent(fusion)
                                    .addComponent(pool)
                                    .addComponent(zorbing)
                                    .addComponent(csgo)
                                    .addComponent(nfs)
                                    .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pubg)
                                    .addComponent(jCheckBox4)
                                    .addComponent(stomp)
                                    .addComponent(basketball)
                                    .addComponent(mrms)
                                    .addComponent(picraaz)
                                    .addComponent(food)
                                    .addComponent(jButton2))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(soccer)
                                    .addComponent(halla)
                                    .addComponent(ball)
                                    .addComponent(snaptext)
                                    .addComponent(fifa))
                                .addGap(216, 216, 216))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vogue)
                    .addComponent(stomp))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(halla))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fantastic)
                    .addComponent(jCheckBox4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soccer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fusion)
                    .addComponent(basketball))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ball))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pool)
                            .addComponent(mrms))))
                .addGap(18, 18, 18)
                .addComponent(snaptext)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ar1)
                    .addComponent(zorbing)
                    .addComponent(picraaz))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ar2)
                    .addComponent(fifa))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(csgo)
                    .addComponent(food))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tr1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(tr2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nfs)
                            .addComponent(pubg))))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tr3)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    private void ar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ar1ActionPerformed

    private void tr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tr1ActionPerformed

    private void hallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hallaActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            int total=0;
            int am =0;
          String sql;
          sql = "insert into datasheet(Booklet,Receipt,Name,Father_Name,Contact,Email,University_CODE,University_ID,Accomodation,Transportation,Event,Amount) values(?,?,?,?,?,?,?,?,?,?,?,?)";
          pst=conn.prepareStatement(sql);
          
          pst.setString(1,t1.getText());
          pst.setString(2,t2.getText());
          pst.setString(3,t3.getText());
          pst.setString(4,t4.getText());
          pst.setString(5,t5.getText());
          pst.setString(6,t6.getText());
          pst.setString(7,t7.getText());
          pst.setString(8,t8.getText());
          if(ar1.isSelected())
          {
              pst.setString(9,"YES");
              am=100;
          }
          else if(ar2.isSelected())
              pst.setString(9, "NO");
          pst.setString(10,"");
          pst.setString(11, "");
          pst.setInt(12, 200);
          if(vogue.isSelected()){
          if(tr1.isSelected())
              pst.setString(10,"43");
          else if(tr2.isSelected())
              pst.setString(10,"17");
          else if(tr3.isSelected())
              pst.setString(10,"NO");
          pst.setString(11, "VOGUE");
          if(am==0)
          pst.setInt(12, 200+am);
          else
          pst.setInt(12, 200);   
          pst.execute();
          }
          if(stomp.isSelected()){
          pst.setString(1,t1.getText());
          pst.setString(2,t2.getText());
          pst.setString(3,t3.getText());
          pst.setString(4,t4.getText());
          pst.setString(5,t5.getText());
          pst.setString(6,t6.getText());
          pst.setString(7,t7.getText());
          pst.setString(8,t8.getText());
          if(ar1.isSelected())
          {
              pst.setString(9,"YES");
              am=100;
          }
          else if(ar2.isSelected())
              pst.setString(9, "NO");
          if(tr1.isSelected())
              pst.setString(10,"43");
          else if(tr2.isSelected())
              pst.setString(10,"NO");
          pst.setString(11, "STOMP THE YARD");
          pst.setInt(12, 200+am);
          pst.execute();
          }
          am=0;
          if(halla.isSelected()){
          pst.setString(1,t1.getText());
          pst.setString(2,t2.getText());
          pst.setString(3,t3.getText());
          pst.setString(4,t4.getText());
          pst.setString(5,t5.getText());
          pst.setString(6,t6.getText());
          pst.setString(7,t7.getText());
          pst.setString(8,t8.getText());
          if(ar1.isSelected())
          {
              pst.setString(9,"YES");
              am=100;
          }
          else if(ar2.isSelected())
              pst.setString(9, "NO");
          if(tr1.isSelected())
              pst.setString(10,"43");
          else if(tr2.isSelected())
              pst.setString(10,"NO");
          pst.setString(11, "HALLA BOL");
          pst.setInt(12, 200+am);
          pst.execute();
          }
          am=0;
          if(fantastic.isSelected()){
          pst.setString(1,t1.getText());
          pst.setString(2,t2.getText());
          pst.setString(3,t3.getText());
          pst.setString(4,t4.getText());
          pst.setString(5,t5.getText());
          pst.setString(6,t6.getText());
          pst.setString(7,t7.getText());
          pst.setString(8,t8.getText());
          if(ar1.isSelected())
          {
              pst.setString(9,"YES");
              am=100;
          }
          else if(ar2.isSelected())
              pst.setString(9, "NO");
          if(tr1.isSelected())
              pst.setString(10,"43");
          else if(tr2.isSelected())
              pst.setString(10,"NO");
          pst.setString(11, "FANTASTIC TOE");
          pst.setInt(12, 150+am);
          pst.execute();
          }
          am=0;
          if(jCheckBox4.isSelected()){
          pst.setString(1,t1.getText());
          pst.setString(2,t2.getText());
          pst.setString(3,t3.getText());
          pst.setString(4,t4.getText());
          pst.setString(5,t5.getText());
          pst.setString(6,t6.getText());
          pst.setString(7,t7.getText());
          pst.setString(8,t8.getText());
          if(ar1.isSelected())
          {
              pst.setString(9,"YES");
              am=100;
          }
          else if(ar2.isSelected())
              pst.setString(9, "NO");
          if(tr1.isSelected())
              pst.setString(10,"43");
          else if(tr2.isSelected())
              pst.setString(10,"NO");
          pst.setString(11, "FOLKLORE");
          pst.setInt(12, 200+am);
          pst.execute();
          }
          am=0;
          if(soccer.isSelected()){
          pst.setString(1,t1.getText());
          pst.setString(2,t2.getText());
          pst.setString(3,t3.getText());
          pst.setString(4,t4.getText());
          pst.setString(5,t5.getText());
          pst.setString(6,t6.getText());
          pst.setString(7,t7.getText());
          pst.setString(8,t8.getText());
          if(ar1.isSelected())
          {
              pst.setString(9,"YES");
              am=100;
          }
          else if(ar2.isSelected())
              pst.setString(9, "NO");
          if(tr1.isSelected())
              pst.setString(10,"43");
          else if(tr2.isSelected())
              pst.setString(10,"NO");
          pst.setString(11, "4 A SIDE SOCCER");
          pst.setInt(12, 150+am);
          pst.execute();
          }
          am=0;
          if(fusion.isSelected()){
          pst.setString(1,t1.getText());
          pst.setString(2,t2.getText());
          pst.setString(3,t3.getText());
          pst.setString(4,t4.getText());
          pst.setString(5,t5.getText());
          pst.setString(6,t6.getText());
          pst.setString(7,t7.getText());
          pst.setString(8,t8.getText());
          if(ar1.isSelected())
          {
              pst.setString(9,"YES");
              am=100;
          }
          else if(ar2.isSelected())
              pst.setString(9, "NO");
          if(tr1.isSelected())
              pst.setString(10,"43");
          else if(tr2.isSelected())
              pst.setString(10,"NO");
          pst.setString(11, "EUPHONIOUS FUSION");
          pst.setInt(12, 150+am);
          pst.execute();
          }
          am=0;
          if(basketball.isSelected()){
          pst.setString(1,t1.getText());
          pst.setString(2,t2.getText());
          pst.setString(3,t3.getText());
          pst.setString(4,t4.getText());
          pst.setString(5,t5.getText());
          pst.setString(6,t6.getText());
          pst.setString(7,t7.getText());
          pst.setString(8,t8.getText());
          if(ar1.isSelected())
          {
              pst.setString(9,"YES");
              am=100;
          }
          else if(ar2.isSelected())
              pst.setString(9, "NO");
          if(tr1.isSelected())
              pst.setString(10,"43");
          else if(tr2.isSelected())
              pst.setString(10,"NO");
          pst.setString(11, "3 ON 3 BASKETBALL");
          pst.setInt(12, 100+am);
          pst.execute();
          }
          am=0;
          if(ball.isSelected()){
          pst.setString(1,t1.getText());
          pst.setString(2,t2.getText());
          pst.setString(3,t3.getText());
          pst.setString(4,t4.getText());
          pst.setString(5,t5.getText());
          pst.setString(6,t6.getText());
          pst.setString(7,t7.getText());
          pst.setString(8,t8.getText());
          if(ar1.isSelected())
          {
              pst.setString(9,"YES");
              am=100;
          }
          else if(ar2.isSelected())
              pst.setString(9, "NO");
          if(tr1.isSelected())
              pst.setString(10,"43");
          else if(tr2.isSelected())
              pst.setString(10,"NO");
          pst.setString(11, "PAINT BALL");
          pst.setInt(12, 150+am);
          pst.execute();
          }
          am=0;
          if(pool.isSelected()){
          pst.setString(1,t1.getText());
          pst.setString(2,t2.getText());
          pst.setString(3,t3.getText());
          pst.setString(4,t4.getText());
          pst.setString(5,t5.getText());
          pst.setString(6,t6.getText());
          pst.setString(7,t7.getText());
          pst.setString(8,t8.getText());
          if(ar1.isSelected())
          {
              pst.setString(9,"YES");
              am=100;
          }
          else if(ar2.isSelected())
              pst.setString(9, "NO");
          if(tr1.isSelected())
              pst.setString(10,"43");
          else if(tr2.isSelected())
              pst.setString(10,"NO");
          pst.setString(11, "8 BALLS OF FIRE");
          pst.setInt(12, 100+am);
          pst.execute();
          }
          am=0;
          if(mrms.isSelected()){
          pst.setString(1,t1.getText());
          pst.setString(2,t2.getText());
          pst.setString(3,t3.getText());
          pst.setString(4,t4.getText());
          pst.setString(5,t5.getText());
          pst.setString(6,t6.getText());
          pst.setString(7,t7.getText());
          pst.setString(8,t8.getText());
          if(ar1.isSelected())
          {
              pst.setString(9,"YES");
              am=100;
          }
          else if(ar2.isSelected())
              pst.setString(9, "NO");
          if(tr1.isSelected())
              pst.setString(10,"43");
          else if(tr2.isSelected())
              pst.setString(10,"NO");
          pst.setString(11, "MR AND MS. ALGORYTHM");
          pst.setInt(12, 100+am);
          pst.execute();
          }
          am=0;
          if(snaptext.isSelected()){
          pst.setString(1,t1.getText());
          pst.setString(2,t2.getText());
          pst.setString(3,t3.getText());
          pst.setString(4,t4.getText());
          pst.setString(5,t5.getText());
          pst.setString(6,t6.getText());
          pst.setString(7,t7.getText());
          pst.setString(8,t8.getText());
          if(ar1.isSelected())
          {
              pst.setString(9,"YES");
              am=100;
          }
          else if(ar2.isSelected())
              pst.setString(9, "NO");
          if(tr1.isSelected())
              pst.setString(10,"43");
          else if(tr2.isSelected())
              pst.setString(10,"NO");
          pst.setString(11, "SNAPTEXT");
          pst.setInt(12, 100+am);
          pst.execute();
          }
          am=0;
          if(zorbing.isSelected()){
          pst.setString(1,t1.getText());
          pst.setString(2,t2.getText());
          pst.setString(3,t3.getText());
          pst.setString(4,t4.getText());
          pst.setString(5,t5.getText());
          pst.setString(6,t6.getText());
          pst.setString(7,t7.getText());
          pst.setString(8,t8.getText());
          if(ar1.isSelected())
          {
              pst.setString(9,"YES");
              am=100;
          }
          else if(ar2.isSelected())
              pst.setString(9, "NO");
          if(tr1.isSelected())
              pst.setString(10,"43");
          else if(tr2.isSelected())
              pst.setString(10,"NO");
          pst.setString(11, "ZORBING");
          pst.setInt(12, 100+am);
          pst.execute();
          }
          am=0;
          if(picraaz.isSelected()){
          pst.setString(1,t1.getText());
          pst.setString(2,t2.getText());
          pst.setString(3,t3.getText());
          pst.setString(4,t4.getText());
          pst.setString(5,t5.getText());
          pst.setString(6,t6.getText());
          pst.setString(7,t7.getText());
          pst.setString(8,t8.getText());
          if(ar1.isSelected())
          {
              pst.setString(9,"YES");
              am=100;
          }
          else if(ar2.isSelected())
              pst.setString(9, "NO");
          if(tr1.isSelected())
              pst.setString(10,"43");
          else if(tr2.isSelected())
              pst.setString(10,"NO");
          pst.setString(11, "PICRAAZ");
          pst.setInt(12, 100+am);
          pst.execute();
          }
          am=0;
          if(fifa.isSelected()){
          pst.setString(1,t1.getText());
          pst.setString(2,t2.getText());
          pst.setString(3,t3.getText());
          pst.setString(4,t4.getText());
          pst.setString(5,t5.getText());
          pst.setString(6,t6.getText());
          pst.setString(7,t7.getText());
          pst.setString(8,t8.getText());
          if(ar1.isSelected())
          {
              pst.setString(9,"YES");
              am=100;
          }
          else if(ar2.isSelected())
              pst.setString(9, "NO");
          if(tr1.isSelected())
              pst.setString(10,"43");
          else if(tr2.isSelected())
              pst.setString(10,"NO");
          pst.setString(11, "FIFA");
          pst.setInt(12, 150+am);
          pst.execute();
          }
          am=0;
          if(csgo.isSelected()){
          pst.setString(1,t1.getText());
          pst.setString(2,t2.getText());
          pst.setString(3,t3.getText());
          pst.setString(4,t4.getText());
          pst.setString(5,t5.getText());
          pst.setString(6,t6.getText());
          pst.setString(7,t7.getText());
          pst.setString(8,t8.getText());
          if(ar1.isSelected())
          {
              pst.setString(9,"YES");
              am=100;
          }
          else if(ar2.isSelected())
              pst.setString(9, "NO");
          if(tr1.isSelected())
              pst.setString(10,"43");
          else if(tr2.isSelected())
              pst.setString(10,"NO");
          pst.setString(11, "CSGO");
          pst.setInt(12, 200+am);
          pst.execute();
          }
          am=0;
          if(food.isSelected()){
          pst.setString(1,t1.getText());
          pst.setString(2,t2.getText());
          pst.setString(3,t3.getText());
          pst.setString(4,t4.getText());
          pst.setString(5,t5.getText());
          pst.setString(6,t6.getText());
          pst.setString(7,t7.getText());
          pst.setString(8,t8.getText());
          if(ar1.isSelected())
          {
              pst.setString(9,"YES");
              am=100;
          }
          else if(ar2.isSelected())
              pst.setString(9, "NO");
          if(tr1.isSelected())
              pst.setString(10,"43");
          else if(tr2.isSelected())
              pst.setString(10,"NO");
          pst.setString(11, "FOOD WITHOUT FIRE");
          pst.setInt(12, 100+am);
          pst.execute();
          }
          am=0;
          if(nfs.isSelected()){
          pst.setString(1,t1.getText());
          pst.setString(2,t2.getText());
          pst.setString(3,t3.getText());
          pst.setString(4,t4.getText());
          pst.setString(5,t5.getText());
          pst.setString(6,t6.getText());
          pst.setString(7,t7.getText());
          pst.setString(8,t8.getText());
          if(ar1.isSelected())
          {
              pst.setString(9,"YES");
              am=100;
          }
          else if(ar2.isSelected())
              pst.setString(9, "NO");
          if(tr1.isSelected())
              pst.setString(10,"43");
          else if(tr2.isSelected())
              pst.setString(10,"NO");
          pst.setString(11, "NEED FOR SPEED");
          pst.setInt(12, 150+am);
          pst.execute();
          }
          am=0;
          if(pubg.isSelected()){
          pst.setString(1,t1.getText());
          pst.setString(2,t2.getText());
          pst.setString(3,t3.getText());
          pst.setString(4,t4.getText());
          pst.setString(5,t5.getText());
          pst.setString(6,t6.getText());
          pst.setString(7,t7.getText());
          pst.setString(8,t8.getText());
          if(ar1.isSelected())
          {
              pst.setString(9,"YES");
              am=100;
          }
          else if(ar2.isSelected())
              pst.setString(9, "NO");
          if(tr1.isSelected())
              pst.setString(10,"43");
          else if(tr2.isSelected())
              pst.setString(10,"NO");
          pst.setString(11, "PUBG");
          pst.setInt(12, 150+am);
          pst.execute();
          }
      }
      catch(HeadlessException e){
          JOptionPane.showMessageDialog(null,e);
          
      } catch (SQLException ex) {
        Logger.getLogger(DataEntry.class.getName()).log(Level.SEVERE, null, ex);
    }
        finally{
            
        }
    setVisible(false);
    DataEntry ob = new DataEntry();
    ob.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void stompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stompActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void poolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poolActionPerformed

    private void mrmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrmsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mrmsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
setVisible(false);
search ob;
    ob = new search();
ob.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ar1;
    private javax.swing.JRadioButton ar2;
    private javax.swing.JCheckBox ball;
    private javax.swing.JCheckBox basketball;
    private javax.swing.JCheckBox csgo;
    private javax.swing.JCheckBox fantastic;
    private javax.swing.JCheckBox fifa;
    private javax.swing.JCheckBox food;
    private javax.swing.JCheckBox fusion;
    private javax.swing.JCheckBox halla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox mrms;
    private javax.swing.JCheckBox nfs;
    private javax.swing.JCheckBox picraaz;
    private javax.swing.JCheckBox pool;
    private javax.swing.JCheckBox pubg;
    private javax.swing.JCheckBox snaptext;
    private javax.swing.JCheckBox soccer;
    private javax.swing.JCheckBox stomp;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JRadioButton tr1;
    private javax.swing.JRadioButton tr2;
    private javax.swing.JRadioButton tr3;
    private javax.swing.JCheckBox vogue;
    private javax.swing.JCheckBox zorbing;
    // End of variables declaration//GEN-END:variables
}
