/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algo;

import com.mysql.jdbc.PreparedStatement;
import java.awt.Event;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;

/**
 *
 * @author Swappy
 */
public class searchbyzone extends javax.swing.JFrame {
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    /**
     * Creates new form searchbyzone
     */
    public searchbyzone() {
        super("Search By Zone");
        initComponents();
        conn = javaconnect.ConnectorDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        zones = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Search By Zone");

        zones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RYTHMRATZ", "ABHIVYAKTI", "SYMPHONY", "GAMEWARP", "FUN-FIESTA" }));

        jLabel2.setText("Amount");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Export");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Total Number of Registrations");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(64, 64, 64)
                        .addComponent(zones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2)
                        .addGap(79, 79, 79)
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addGap(265, 265, 265)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(zones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        search ob = new search();
        ob.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String zone = zones.getSelectedItem().toString();
            if(zone == "RYTHMRATZ"){
                String sql = "select Name, Contact, University_CODE, University_ID, Event from DataSheet where Event = \'VOGUE\' OR Event = \'FOLKLORE\' OR Event = \'STOMP THE YARD\' OR Event = \'FANTASTIC TOE\'";
            pst = (PreparedStatement) conn.prepareStatement(sql);
            rs= pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));
            String sql1 = "select sum(Amount) from DataSheet where Event = \'VOGUE\' OR Event = \'VOGUE\' OR Event = \'FOLKLORE\' OR Event = \'STOMP THE YARD\' OR Event = \'FANTASTIC TOE\'";
            pst = (PreparedStatement) conn.prepareStatement(sql1);
            rs = pst.executeQuery();
            if(rs.next()){
                String sum = rs.getString("sum(amount)");
                t1.setText(sum);
            }
            String sql2 ="select count(Receipt) from DataSheet where Event = \'VOGUE\' OR Event = \'VOGUE\' OR Event = \'FOLKLORE\' OR Event = \'STOMP THE YARD\' OR Event = \'FANTASTIC TOE\'";
            pst = (PreparedStatement) (java.sql.PreparedStatement) conn.prepareStatement(sql2);
            rs = pst.executeQuery();
            if(rs.next()){
                String count = rs.getString("count(Receipt)");
                t2.setText(count);
                
            }
            }
            else if(zone == "ABHIVYAKTI"){
                String sql = "select Name, Contact, University_CODE, University_ID, Event from DataSheet where Event = \'HALLA BOL\'";
            pst = (PreparedStatement) conn.prepareStatement(sql);
            rs= pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));
            String sql1 = "select sum(Amount) from DataSheet where Event = \'HALLA BOL\'";
            pst = (PreparedStatement) conn.prepareStatement(sql1);
            rs = pst.executeQuery();
            if(rs.next()){
                String sum = rs.getString("sum(amount)");
                t1.setText(sum);
            }
            String sql2 ="select count(Receipt) from DataSheet where Event = \'HALLA BOL\'";
            pst = (PreparedStatement) (java.sql.PreparedStatement) conn.prepareStatement(sql2);
            rs = pst.executeQuery();
            if(rs.next()){
                String count = rs.getString("count(Receipt)");
                t2.setText(count);
                
            }
            }
            else if(zone == "GAMEWARP"){
                String sql = "select Name, Contact, University_CODE, University_ID, Event from DataSheet where Event = \'FIFA\' OR Event = \'4 A SIDE SOCCER\' OR Event = \'CSGO\' OR Event = \'8 BALLS OF FIRE\' OR Event = \'3 ON 3 BASKETBALL\' OR Event = \'NEED FOR SPEED\' OR EVENT = \'PUBG\'";
            pst = (PreparedStatement) conn.prepareStatement(sql);
            rs= pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));
            String sql1 = "select sum(Amount) from DataSheet where Event = \'FIFA\' OR Event = \'4 A SIDE SOCCER\' OR Event = \'CSGO\' OR Event = \'8 BALLS OF FIRE\' OR Event = \'3 ON 3 BASKETBALL\' OR Event = \'NEED FOR SPEED\' OR EVENT = \'PUBG\'";
            pst = (PreparedStatement) conn.prepareStatement(sql1);
            rs = pst.executeQuery();
            if(rs.next()){
                String sum = rs.getString("sum(amount)");
                t1.setText(sum);
            }
            String sql2 ="select count(Receipt) from DataSheet where Event = \'FIFA\' OR Event = \'4 A SIDE SOCCER\' OR Event = \'CSGO\' OR Event = \'8 BALLS OF FIRE\' OR Event = \'3 ON 3 BASKETBALL\' OR Event = \'NEED FOR SPEED\' OR EVENT = \'PUBG\'";
            pst = (PreparedStatement) (java.sql.PreparedStatement) conn.prepareStatement(sql2);
            rs = pst.executeQuery();
            if(rs.next()){
                String count = rs.getString("count(Receipt)");
                t2.setText(count);
                
            }
            }
            else if(zone == "SYMPHONY"){
                String sql = "select Name, Contact, University_CODE, University_ID, Event from DataSheet where Event = \'EUPHONIOUS FUSION\'";
            pst = (PreparedStatement) conn.prepareStatement(sql);
            rs= pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));
            String sql1 = "select sum(Amount) from DataSheet where Event = \'EUPHONIOUS FUSION\'";
            pst = (PreparedStatement) conn.prepareStatement(sql1);
            rs = pst.executeQuery();
            if(rs.next()){
                String sum = rs.getString("sum(amount)");
                t1.setText(sum);
            }
            String sql2 ="select count(Receipt) from DataSheet where Event = \'EUPHONIOUS FUSION\'";
            pst = (PreparedStatement) (java.sql.PreparedStatement) conn.prepareStatement(sql2);
            rs = pst.executeQuery();
            if(rs.next()){
                String count = rs.getString("count(Receipt)");
                t2.setText(count);
                
            }
            }
            else if(zone == "FUN-FIESTA"){
                String sql = "select Name, Contact, University_CODE, University_ID, Event from DataSheet where Event = \'SNAPTEXT\' OR Event = \'MR AND MS. ALGORYTHM\' OR Event = \'PAINT BALL\' OR Event = \'ZORBING\' OR Event = \'PICRAAZ\' OR Event = \'FOOD WITHOUT FIRE\'";
            pst = (PreparedStatement) conn.prepareStatement(sql);
            rs= pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));
            String sql1 = "select sum(Amount) from DataSheet where Event = \'SNAPTEXT\' OR Event = \'MR AND MS. ALGORYTHM\' OR Event = \'PAINT BALL\' OR Event = \'ZORBING\' OR Event = \'PICRAAZ\' OR Event = \'FOOD WITHOUT FIRE\'";
            pst = (PreparedStatement) conn.prepareStatement(sql1);
            rs = pst.executeQuery();
            if(rs.next()){
                String sum = rs.getString("sum(amount)");
                t1.setText(sum);
            }
            String sql2 ="select count(Receipt) from DataSheet where Event = \'SNAPTEXT\' OR Event = \'MR AND MS. ALGORYTHM\' OR Event = \'PAINT BALL\' OR Event = \'ZORBING\' OR Event = \'PICRAAZ\' OR Event = \'FOOD WITHOUT FIRE\'";
            pst = (PreparedStatement) (java.sql.PreparedStatement) conn.prepareStatement(sql2);
            rs = pst.executeQuery();
            if(rs.next()){
                String count = rs.getString("count(Receipt)");
                t2.setText(count);
                
            }
            }
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(searchbybooklet.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String excelFileName = "C:\\Users\\Swappy\\Documents\\Algorythm\\Zone\\"+zones.getSelectedItem().toString()+".xls";//name of excel file
                TableModel model = table.getModel();
		String sheetName = "Sheet1";//name of sheet

		HSSFWorkbook wb = new HSSFWorkbook();
		HSSFSheet sheet = wb.createSheet(sheetName) ;
                HSSFRow row = sheet.createRow(0);
                for(int i=0;i<model.getColumnCount();i++){
                    HSSFCell cell = row.createCell(i);
                    cell.setCellValue(model.getColumnName(i));
                }
		for (int r=1;r <= model.getRowCount(); r++ )
		{
			 row = sheet.createRow(r);
	
			//iterating c number of columns
			for (int c=0;c < model.getColumnCount(); c++ )
			{
				HSSFCell cell = row.createCell(c);
				
				cell.setCellValue(model.getValueAt(r-1,c).toString());
			}
		}
		
		FileOutputStream fileOut = null;
        try {
            fileOut = new FileOutputStream(excelFileName);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(searchbyevent.class.getName()).log(Level.SEVERE, null, ex);
        }
		
        try {
            //write this workbook to an Outputstream.
            wb.write(fileOut);
        } catch (IOException ex) {
            Logger.getLogger(searchbyevent.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            fileOut.flush();
        } catch (IOException ex) {
            Logger.getLogger(searchbyevent.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            fileOut.close();
        } catch (IOException ex) {
            Logger.getLogger(searchbyevent.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
        searchbyzone ob = new searchbyzone();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchbyzone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchbyzone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchbyzone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchbyzone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchbyzone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTable table;
    private javax.swing.JComboBox<String> zones;
    // End of variables declaration//GEN-END:variables
}
